### ISSUE TITLE
lack of torchsample module

### ISSUE THREAD

**Issue by lyupei** [lxy5513/videopose#1]
git clone --recursive don't work.
fatal: no submodule mapping found in .gitmodules for path 'Alphapose/src/torchsample'

**Comment by lyupei** [comment]
I've installed the torchsample module and finally run it successfully.

But I can't find the 'cpn-pt-243.bin' so I used the 'pretrained_h36m_cpn.bin'.

But I got wrong result in Reconstruction with dancing.mp4 and taiji.mp4.

Is this the expectant result?

**Comment by lyupei** [comment]
I tested with other videos, seems that the keypoint order is wrong.

**Comment by lyupei** [comment]
Now it works well on cpn-pt-243.bin.
Thanks a lot.

**Comment by Ssrzbao** [comment]
> Now it works well on cpn-pt-243.bin.
> Thanks a lot.

Have you ever encountered a problem with the file path of ‘ffprobe’?  the problem occurs in File "/videopose-master/common/visualization.py", line 22, in get_resolution
    with sp.Popen(command, stdout=sp.PIPE, bufsize=-1) as pipe:

 How did you get cpn-pt-243.bin?

**Comment by lyupei** [comment]
> > Now it works well on cpn-pt-243.bin.
> > Thanks a lot.
> 
> Have you ever encountered a problem with the file path of ‘ffprobe’? the problem occurs in File "/videopose-master/common/visualization.py", line 22, in get_resolution
> with sp.Popen(command, stdout=sp.PIPE, bufsize=-1) as pipe:
> 
> How did you get cpn-pt-243.bin?

I downloaded from here: https://dl.fbaipublicfiles.com/video-pose-3d/cpn-pt-243.bin

**Comment by lxy5513** [comment]
Sorry for that I see it just now. the problem seem have solved, 
I close this issue.
