### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by manansaxena** [lxy5513/videopose#10]
Hi, 
1)I want to run this and want to use the openpose for 2D joint locations.
Could you please give a brief of how are we supposed to run this for our own video?
2) While running op_video on google colab i get the following error
File "op_video.py", line 149, in <module>
    main()
  File "op_video.py", line 88, in main
    keypoints = normalize_screen_coordinates(keypoints[..., :2], w=1000, h=1002)
  File "/content/videopose/tools/../common/camera.py", line 15, in normalize_screen_coordinates
    assert X.shape[-1] == 2
AssertionError
Thanks for your help

**Comment by lxy5513** [comment]
1. complie openpose python API env  
2. run video.py 

> keypoints = normalize_screen_coordinates(keypoints[..., :2], w=1000, h=1002)
File "/content/videopose/tools/../common/camera.py", line 15, in normalize_screen_coordinates
assert X.shape[-1] == 2
AssertionError 

you need check the keypoints, maybe your keypoints is []

**Comment by manansaxena** [comment]
Thanks for the help, its working now!
I also needed your advice on how can I make this work for a particular person in a multi-person video?
Is it possible to do so ?
Thanks

**Comment by lxy5513** [comment]
you need a tracking algorithm to point out particular person in your video, and extract its bounding box, then feed to 2D detector and VideoPose3D.
