### ISSUE TITLE
Modifying hrnet_video.py ?

### ISSUE THREAD

**Issue by tonoim** [lxy5513/videopose#11]
Hello ,  I can extract the `coco_keypoints` from `posenet` and also `a simple hrnet` implementation. which basically returns , `keypoints` and `confidence scores` perframe  . I was wondering if i can plug those into the `hrnet_video.py` ? What are the reuquirements on that and where should i do , the changes if possible ? If i understand correctly you only care about the returned `2D keypoints` and `confidence scores ` for each predicted keypoints.

**Comment by lxy5513** [comment]
https://github.com/lxy5513/videopose/blob/master/tools/hrnet_video.py#L76
```
        from joints_detectors.hrnet.pose_estimation.video import generate_kpts
        video_name = args.viz_video
        print('generat keypoints by hrnet...')
        keypoints = generate_kpts(video_name)
```

yes, you only need return 2D keypoints
