### ISSUE TITLE
One image or video with multiple people, camera matrix

### ISSUE THREAD

**Issue by civilpat** [lxy5513/videopose#12]
Hi, thanks very much for your work! I have some questions: (1) can this code run on multiple people 3d pose estimation? (2)can it be performed on one image or has to be on a video? (3) Do you have to input camera matrix for lifting 2D pose to 3D pose? Or the camera matrix can be calculated in the algorithm? I appreciate your help.

**Comment by lxy5513** [comment]
Hi, 1. VideoPose3D don't support multiple people 3d pose estimation.   
2. It has to be performed on video.   
3. you don't have to  camera matrix.  input 2D image translate(inference) to 3D joints in camera space and we provide a matrix, translate it to world space.

**Comment by skyler1537** [comment]
Hi @lxy5513 - it looks like you have done some great work in this space.  Does this repo run in real time?  Do you know the FPS given your hardware specs?

**Comment by lxy5513** [comment]
Yes it can run in real time. The speed mostly depend on your 2d key point detector. I run video with it's frame resolution is 640×360 ， the speed is 30fps. I use two 1080ti gpu

**Comment by skyler1537** [comment]
Awesome - did you use your hrnet repo to train the 2D model as well? Using the center and scale generated from the Yolo model? Is that the right pipeline to be thinking about for custom training?

**Comment by lxy5513** [comment]
Yes ，it's right pipeline
