### ISSUE TITLE
Inference speed.

### ISSUE THREAD

**Issue by skyler1537** [lxy5513/videopose#14]
Hey @lxy5513  - you've done some great work in this repo.  I've got an HRNet version up and running now on an aws p3 instance (Nvidia V100) - and it's running at about 3 FPS.  I'm curious how you parallelized the operations to achieve 30 FPS? I'm also showing that the drawing function (draw_3img from tools/utils.py) is about 1/3 of the processing time per frame.  What are your thoughts for speedup there?

**Comment by lxy5513** [comment]
I get 25+ FPS by openpose which test video resolution is 640*360.  but use hrnet I also get 15+FPS speed by 1 1080Ti.    

`draw_3img from tools/utils.py` use opencv2 to draw 3D image, It slow. the high speed method is use pyqtgraph in https://github.com/lxy5513/videopose/blob/master/tools/amination.py 

by the way, what's 2D keypoints detection speed? It should over 25FPS at least by Nvidia V100

**Comment by skyler1537** [comment]
Maybe that's part of my problem - I'm only getting about 10 FPS with the V100 for the HRNet 2D portion.  

I'm using:
from joints_detectors.hrnet.pose_estimation.video import getKptsFromImage
joint2D = getKptsFromImage(yolo_model,hrnet_model,frame, smooth=True) 

I'll swap i the animation file and see what improvement that might make.

**Comment by lxy5513** [comment]
maybe you can try the new `python tools/hrnet_video.py` without smooth .
