### ISSUE TITLE
"python tools/hrnet_video.py "error?

### ISSUE THREAD

**Issue by huangshaoguang** [lxy5513/videopose#15]
Hello! Thank you for sharing! I get an error when I run "python tools/hrnet_video.py", could you please help me?
 python tools/hrnet_video.py --viz-video data/example_dance.mp4
Loading YOLO network.....
Network successfully loaded
generat keypoints by hrnet...
  0%|                                                   | 0/401 [00:00<?, ?it/s]/home/admin888/.local/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
100%|█████████████████████████████████████████| 401/401 [00:18<00:00, 22.00it/s]
------- load data spends 23.01 seconds
Loading checkpoint /home/admin888/Desktop/BodyPose/videopose/tools/../checkpoint/cpn-pt-243.bin
/home/admin888/Desktop/BodyPose/videopose/tools/..
------- load 3D model spends 0.10 seconds
Rendering...
------- generate reconstruction 3D data spends 0.01 seconds
Traceback (most recent call last):
  File "tools/hrnet_video.py", line 151, in <module>
    main()
  File "tools/hrnet_video.py", line 144, in main
    input_video_skip=args.viz_skip)
  File "/home/admin888/Desktop/BodyPose/videopose/tools/../common/visualization.py", line 136, in render_animation
    for f in read_video(input_video_path, skip=input_video_skip):
  File "/home/admin888/Desktop/BodyPose/videopose/tools/../common/visualization.py", line 39, in read_video
    w, h = get_resolution(filename)
  File "/home/admin888/Desktop/BodyPose/videopose/tools/../common/visualization.py", line 33, in get_resolution
    with sp.Popen(command, stdout=sp.PIPE, bufsize=-1) as pipe:
  File "/home/admin888/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/admin888/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by lxy5513** [comment]
Actually you have already generate the 3D joints, the problem is that visualization. you need to create a  folder `ffprobe`

**Comment by huangshaoguang** [comment]
Thank you for replying! I solved it by installing FFmpeg dependence(apt-get install).

**Comment by lxy5513** [comment]
👍 ,  you can also try realtime display like https://github.com/lxy5513/videopose/blob/master/tools/utils.py#L79 or high speed realtime diplay like  `videopose/tools/amination.py`
