### ISSUE TITLE
Can it predict online?

### ISSUE THREAD

**Issue by huangshaoguang** [lxy5513/videopose#16]
Hello! Thank you for your great job. If I want to predict a pose with 3D,can it predict online?

**Comment by lxy5513** [comment]
yes, It can predict online, you can see the demo https://github.com/lxy5513/videopose/blob/master/outputs/README.md

**Comment by huangshaoguang** [comment]
Thank you very much. I will try it

**Comment by huangshaoguang** [comment]
Is it only the result? There is no code

**Comment by lxy5513** [comment]
The code is in tools/animation.py
