### ISSUE TITLE
what the skeleton order are like?

### ISSUE THREAD

**Issue by wongkwan** [lxy5513/videopose#17]
when I run the alphapose_video.py using my own trained model, the result is not right ,because the  skeleton order in my trained model is different to the skeleton order in the model cpn-pt-243.bin you provided, so can you tell me what  the skeleton order and skeleton_parent list are like?

**Comment by lxy5513** [comment]
2d keypoints order is coco format: 

![image](https://user-images.githubusercontent.com/39720528/62278972-be686300-b47b-11e9-863e-e9c677da1a9f.png)

keypoints_symmetry: [[1, 3, 5, 7, 9, 11, 13, 15],[2, 4, 6, 8, 10, 12, 14, 16]]   
sleleton_parents:  [-1,  0,  1,  2,  0,  4,  5,  0,  7,  8,  9,  8, 11, 12,  8, 14, 15] 


Actually, you only need input the 2d keypints order to videopose model:
['nose', 'l_eye', 'r_eye', 'l_ear', 'r_ear', 'l_shoulder',
    'r_shoulder', 'l_elbow', 'r_elbow', 'l_wrist', 'r_wrist',
    'l_hip', 'r_hip', 'l_knee', 'r_knee', 'l_ankle', 'r_ankle']

**Comment by wongkwan** [comment]
can you tell me how to convert the 2d keypoints order to videopose model ?thank you so much if you can help me.

**Comment by wongkwan** [comment]
I want to know how is the cpn-pt-243.bin trained?

**Comment by lxy5513** [comment]
the  cpn-pt-243.bin I download from https://dl.fbaipublicfiles.com/video-pose-3d/cpn-pt-243.bin . 

You only need make up the (N, 17, 2) data format, which order I mentioned. than do normlization, than feed the videopose model.
