### ISSUE TITLE
comparison with 3d baselne

### ISSUE THREAD

**Issue by timtensor** [lxy5513/videopose#2]
Hi do you think there could be a good comparison to the 3d estimated pose for example the following ? 

[https://github.com/una-dinosauria/3d-pose-baseline](https://github.com/una-dinosauria/3d-pose-baseline)

**Comment by lxy5513** [comment]
@timtensor  
I am not very sure,   demo video in https://github.com/una-dinosauria/3d-pose-baseline is human3.6m videos, which is in special scene. so I don't know what's the effect on wild video.

**Comment by timtensor** [comment]
HI thanks , for the reply. There is a fork , which does some kind of 3d pose estimation in the wild . So i was curious. Link for the fork [https://github.com/ArashHosseini/3d-pose-baseline](https://github.com/ArashHosseini/3d-pose-baseline)

**Comment by lxy5513** [comment]
from my personal opinion, the `videopose` better a little.  I feel the `3d-pose-baseline` reconstruction video some like stiff.   
However, I am not professional in this field， just know a little.   
For more, you can test two model in human3.6M Under Protocol 1 (mean per-joint position error) and Protocol 2 (mean-per-joint position error after rigid alignment)

**Comment by basicvisual** [comment]
ok , thanks a lot for your info. I will try out video pose. If i understand correctly first `hrnet` does 2d pose estimation and then you apply `alphaspose ` to get 3d pose estimation from keypoints right ? 

A follow up question, does `hrnet_video.py` do a 3d pose estimation of an input video as well ?? I got a bit confused . Also , do you have a detailed document on the requirements and installations ?
