### ISSUE TITLE
可以提供一个input_name.npz吗？没有--input-npz 参数每次加载到76%就会终止

### ISSUE THREAD

**Issue by Scheaven** [lxy5513/videopose#20]
可以提供一个input_name.npz吗？没有--input-npz 参数每次加载到76%就会终止

**Comment by Scheaven** [comment]
path文件夹由于没有找到，所以希望获得帮助，谢谢

**Comment by lxy5513** [comment]
你可以把具体运行的python文件和错误信息写出来吗？

**Comment by Scheaven** [comment]
(py3_pytorch) E:\project\pytorch\videopose> python tools/hrnet_video.py --viz-video ./111.mp4
Loading YOLO network.....
Network successfully loaded
generat keypoints by hrnet...
  0%|                                                                                                                                                                                                               | 0/147 [00:00<?, ?it/s]C:\Users\Scheaven\Anaconda3\envs\py3_pytorch\lib\site-packages\torch\nn\modules\upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
  1%|█▎          
 1%|██▋                                                                                                                                                                                                    | 2/147 [00:08<13:50,  5.73s/i  2%|████                                                                                                                                                                                                   | 3/147 [00:08<09:44,  4.06s/  3%|█████▍                                                                                                                                                                                                 | 4/147 [00:08<06:51,  2.88s  3%|██████▊                                                                                                                                                                                                | 5/147 [00:08<04:51,  2.0  4%|████████                                                                                                                                                                                               | 6/147 [00:08<03:27,  1.  5%|█████████▍                                                                                                                                                                                             | 7/147 [00:08<02:29,  1  5%|██████████▊                                                                                                                                                                                            | 8/147 [00:09<01:48,   6%|████████████▏                                                                                                                                                                                          | 9/147 [00:09<01:21,  7%|█████████████▍                                                                                                                                                                                        | 10/147 [00:09<01:01  7%|██████████████▊                                                                                                                                                                                       | 11/147 [00:09<00:  8%|████████████████▏                                                                                                                                                                                     | 12/147 [00:09<00  9%|█████████████████▌                                                                                                                                                                                    | 13/147 [00:09<0 10%|██████████████████▊                                                                                                                                                                                   | 14/147 [00:09 10%|████████████████████▏                                                                                                                                                                                 | 15/147 [00:09<00:24,  5.45it/s]expected a non-empty list of Tensors
 11%|█████████████████████▌                                                                                                                                                                                | 16/147 [00:10<00:23,  5.50it/s]expected a non-empty list of Tensors
expected a non-empty list of Tensors
 12%|████████████████████████▏                                                                                                                                                                             | 18/147 [00:10<00:19,  6.77it/s]expected a non-empty list of Tensors
 14%|██████████████████████████▉                                                                                                                                                                           | 20/14 14%|████████████████████████████▎                                                                                                                                                                         | 21/1 15%|█████████████████████████████▋                                                                                                                                                                        | 22/147 [00:10<00:15,  7.81it/s]expected a non-empty list of Tensors
 16%|████████████████████████████████▎                                                                                                                                                                     |  17%|█████████████████████████████████▋                                                                                                                                                                     18%|███████████████████████████████████                                                                                                                                                                   18%|████████████████████████████████████▎                                                                                                                                                                 | 27/147 [00:11<00:14,  8.26it/s]expected a non-empty list of Tensors
 20%|███████████████████████████████████████                                                                                                                                                           20%|████████████████████████████████████████▍                                                                                                                                                        21%|█████████████████████████████████████████▊                                                                                                                                                     22%|███████████████████████████████████████████                                                                                                                                                   22%|████████████████████████████████████████████▍                                                                                                                                                23%|█████████████████████████████████████████████▊                                                                                                                                             24%|███████████████████████████████████████████████▏                                                                                                                                          24%|████████████████████████████████████████████████▍                                                                                                                                        25%|█████████████████████████████████████████████████▊                                                                                                                                     26%|███████████████████████████████████████████████████▏                                                                                                                                  27%|████████████████████████████████████████████████████▌                                                                                                                                27%|█████████████████████████████████████████████████████▉                                                                                                                             28%|███████████████████████████████████████████████████████▏                                                                                                                          29%|████████████████████████████████████████████████████████▌                                                                                                                        29%|█████████████████████████████████████████████████████████▉                                                                                                                     30%|███████████████████████████████████████████████████████████▎                                                                                                                  31%|████████████████████████████████████████████████████████████▌                                                                                                                31%|█████████████████████████████████████████████████████████████▉                                                                                                             32%|███████████████████████████████████████████████████████████████▎                                                                                                          33%|████████████████████████████████████████████████████████████████▋                                                                                                       33%|██████████████████████████████████████████████████████████████████                                                                                                     34%|███████████████████████████████████████████████████████████████████▎                                                                                                  35%|████████████████████████████████████████████████████████████████████▋                                                                                               35%|██████████████████████████████████████████████████████████████████████                                                                                             36%|███████████████████████████████████████████████████████████████████████▍                                                                                          37%|████████████████████████████████████████████████████████████████████████▋                                                                                       37%|██████████████████████████████████████████████████████████████████████████                                                                                     38%|███████████████████████████████████████████████████████████████████████████▍                                                                                  39%|████████████████████████████████████████████████████████████████████████████▊                                                                               39%|██████████████████████████████████████████████████████████████████████████████                                                                             40%|███████████████████████████████████████████████████████████████████████████████▍                                                                          41%|████████████████████████████████████████████████████████████████████████████████▊                                                                       41%|██████████████████████████████████████████████████████████████████████████████████▏                                                                    42%|███████████████████████████████████████████████████████████████████████████████████▌                                                                  43%|████████████████████████████████████████████████████████████████████████████████████▊                                                               44%|██████████████████████████████████████████████████████████████████████████████████████▏                                                            44%|███████████████████████████████████████████████████████████████████████████████████████▌                                                          45%|████████████████████████████████████████████████████████████████████████████████████████▉                                                       46%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                    46%|███████████████████████████████████████████████████████████████████████████████████████████▌                                                  47%|████████████████████████████████████████████████████████████████████████████████████████████▉                                               48%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                            48%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                         49%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                       50%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                                    50%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                 51%|█████████████████████████████████████████████████████████████████████████████████████████████████████                               52%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                            52%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                         53%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                       54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    54%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████               56%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            56%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         57%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      58%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ 59%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 61%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 61%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 63%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 63%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 69%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 69%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 105/147 [00:21<00:05,  8.05it/s]expected a non-empty list of Tensors
expected a non-empty list of Tensors
 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 111/147 [00:21<00:04,  8.66it/s]expected a non-empty list of Tensors
No detections were made
 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                | 111/147 [00:21<00:07,  5.06it/s]

(py3_pytorch) E:\project\pytorch\videopose>

**Comment by lxy5513** [comment]
你这可能不是程序的问题 ，你换一个短一点的视频试试。

**Comment by Scheaven** [comment]
感谢您的耐心，我换成了一个两秒的短视频，这次可以完成加载，但是最后的时候报错找不到文件。。。
python tools/hrnet_video.py --viz-video ./12.mp4
... ...
------- load data spends 17.28 seconds
Loading checkpoint E:\project\pytorch\videopose\tools\..\checkpoint\cpn-pt-243.bin
------- load 3D model spends 0.18 seconds
Rendering...
------- generate reconstruction 3D data spends 0.02 seconds
======== None
======== outputs/hrnet_result.mp4
Traceback (most recent call last):
  File "tools/hrnet_video.py", line 151, in <module>
    main()
  File "tools/hrnet_video.py", line 144, in main
    input_video_skip=args.viz_skip)
  File "E:\project\pytorch\videopose\tools\..\common\visualization.py", line 136, in render_animation
    for f in read_video(input_video_path, skip=input_video_skip):
  File "E:\project\pytorch\videopose\tools\..\common\visualization.py", line 39, in read_video
    w, h = get_resolution(filename)
  File "E:\project\pytorch\videopose\tools\..\common\visualization.py", line 33, in get_resolution
    with sp.Popen(command, stdout=sp.PIPE, bufsize=-1) as pipe:
  File "C:\Users\Scheaven\Anaconda3\envs\py3_pytorch\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Scheaven\Anaconda3\envs\py3_pytorch\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by Scheaven** [comment]
我对问题进行了定位，发现应该是pipe读取文件时的问题，但是不知道怎么修改。望指教
visualization.py文件的源码如下
    with sp.Popen(command, stdout = sp.PIPE, bufsize=-1) as pipe:
        while True:
            data = pipe.stdout.read(w*h*3)
            if not data:
                break
            i += 1
            if i > skip:
                yield np.frombuffer(data, dtype='uint8').reshape((h, w, 3))
            if i == limit:
                break

**Comment by lxy5513** [comment]
不好意思，可能是subprocess版本问题？我也不太清楚。

**Comment by lxy5513** [comment]
[hrnet.zip](https://github.com/lxy5513/videopose/files/3553987/hrnet.zip)
ni你可以试试这个，我自己写的可视化代码

**Comment by Scheaven** [comment]
还是报错...你那边遇见过这些错误吗？
(py3_pytorch) E:\project\pytorch\videopose> python hrnet_realtime.py --viz-video ./111.mp4
Loading YOLO network.....
Network successfully loaded
Traceback (most recent call last):
  File "hrnet_realtime.py", line 10, in <module>
    bboxModel, poseModel = getTwoModel()
  File "E:\project\pytorch\videopose\joints_detectors\hrnet\pose_estimation\video.py", line 152, in getTwoModel
    pose_model = model_load(cfg)
  File "E:\project\pytorch\videopose\joints_detectors\hrnet\pose_estimation\video.py", line 77, in model_load
    config, is_train=False
  File "E:\project\pytorch\videopose\joints_detectors\hrnet\pose_estimation\..\lib\models\pose_hrnet.py", line 496, in get_pose_net
    model = PoseHighResolutionNet(cfg, **kwargs)
  File "E:\project\pytorch\videopose\joints_detectors\hrnet\pose_estimation\..\lib\models\pose_hrnet.py", line 291, in __init__
    self.stage2_cfg = cfg['MODEL']['EXTRA']['STAGE2']
KeyError: 'STAGE2'

**Comment by lxy5513** [comment]
I have fixed the error, you can pull the code 

 run `python tools/hrnet_realtime.py -video /path/to/video.mp4`

**Comment by Scheaven** [comment]
非常感谢，已经顺利运行，后期会详细阅读代码，感谢帮助，也希望后边能为项目做一些贡献

**Comment by lxy5513** [comment]
😊
