### ISSUE TITLE
【realtime question】hrnet_realtime 中 使用webcamera ，速度慢

### ISSUE THREAD

**Issue by WinstonDeng** [lxy5513/videopose#24]
您好，我在hrnet_realtime.py中使用了本地摄像头，可以使用，但是很慢，统计了时间，出一个3d 结果需要 1.3 s 左右，其中 hrnet 得到 2d 结果需要 0.9 s ，我这里主要是 darknet 的 forward 处理用了 0.6 s，但是 yolo+darknet 本身不是很快吗，所以想问一下是什么原因，您有遇到类似的问题吗？

**Comment by lxy5513** [comment]
你的gpu显卡和CUDA版本用的是什么呢？

**Comment by WinstonDeng** [comment]
GT710,  cuda 9.0.  讲道理 hrnet 0.3 s, rnn 0.1 s，就是 yolo 0.6 s ,感觉很迷

**Comment by lxy5513** [comment]
可能是显卡不太好吧，但你这也太慢了。我也不太清楚了

**Comment by WinstonDeng** [comment]
解决了。换了1080的卡试了一下，一帧 0.1 s。看来是我的卡太laji了。。。

**Comment by sivlab** [comment]
@WinstonDeng could you tell me how to run the "hrnet_realtime.py"? I have to install or download something?

**Comment by WinstonDeng** [comment]
> @WinstonDeng could you tell me how to run the "hrnet_realtime.py"? I have to install or download something?

**Follow the readme.md, and ensure that you have download the pre-trained models.** 

**If you want to use hrnet to get 2d pose and then infer 3d pose by videopose, you need download 3 files:**

- yolov3 model : `wget https://pjreddie.com/media/files/yolov3.weights`

- hrnet model: https://drive.google.com/drive/folders/1nzM_OBV9LbAEA7HClC0chEyf_7ECDXYA

- videopose model: https://dl.fbaipublicfiles.com/video-pose-3d/cpn-pt-243.bin

**Finally, run this code:**

`python tools/hrnet_realtime.py -video /path/to/video.mp4`

**Comment by CuiSQ** [comment]
@WinstonDeng 您好，想请教您是如何在hrnet_realtime.py使用本地摄像头的呢？
