### ISSUE TITLE
Live 3d estimation

### ISSUE THREAD

**Issue by andriy-tsvikla** [lxy5513/videopose#26]
Hi. Can you please describe your configuration for live streaming.
Video height/width , fps?
Did you tried live estimation only with hrnet or did you used other models?
Did you used one GPU or multiple?

Because i am trying to use your example with openpose on single GPU and having some performance issues and trying to figure out the problem.
Thanks.

**Comment by lxy5513** [comment]
I use 2 1080ti GPU , generate 2d keypoints by openpose , can get speed of 25PFS+.

The test video resolution is 640*480

**Comment by andriy-tsvikla** [comment]
Thank you.
