### ISSUE TITLE
如何进行重新训练模型呢？

### ISSUE THREAD

**Issue by Scheaven** [lxy5513/videopose#28]
运行已经成功，但是会是不是的提示
RuntimeError: expected a non-empty list of Tensors

并且感觉3D显示那边的更新有延时，或者有时虽然监测到了人，17个点的位置信息却没有被返回

另外我想重新训练cpn骨骼点识别模型和3D映射模型，如何重新训练呢？

**Comment by lxy5513** [comment]
最近很忙， 抱歉这么久才回复

重新训练的话请参考这里  
https://github.com/facebookresearch/VideoPose3D

实时延迟的话可能是GPU处理速度比较慢，也可能是3D显示方面比较慢， 建议使用pyqtgraph, 执行`python amination.py`, 我可以达到25FPS的速度。   
还不行的话，你可以考虑丢弃帧，比如每三帧只处理两帧
