### ISSUE TITLE
I wanna know how to run the Demo in RealTime WebCam

### ISSUE THREAD

**Issue by doubleZ222** [lxy5513/videopose#30]
Hello ,as the title

**Comment by lxy5513** [comment]
First, you need install and compile openpose and it's python implement  
then install pyqtgraph 
last run `python amination.py`

**Comment by doubleZ222** [comment]
Thanks for your help! It does works.

**Comment by sivlab** [comment]
@doubleZ222 can you explain me how "install and compile" openpose? There are files I have to put in the "joints_detectors"?
