### ISSUE TITLE
KeyError: "filename 'storages' not found"

### ISSUE THREAD

**Issue by lisa676** [lxy5513/videopose#32]
Hi @lxy5513  thanks so much for your such a nice work. It's really helpful. I tried to run following file

`python tools/hrnet_video.py -video path_to_video`

I got following error, I don't know how to solve this problem?

![Capture](https://user-images.githubusercontent.com/40846865/69623672-4a7f4580-107e-11ea-9452-b72c65cbc386.PNG)

**Comment by lxy5513** [comment]
@lan786  so can you print the "model_file_name"?
