### ISSUE TITLE
from openpose import pyopenpose as op求助

### ISSUE THREAD

**Issue by wangxiaobai2268** [lxy5513/videopose#35]
from openpose import pyopenpose as op
ModuleNotFoundError: No module named 'openpose'
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
打扰了，我想问一下上面的问题应该怎么解决？

**Comment by lxy5513** [comment]
你需要先编译运行openpose python

**Comment by wangxiaobai2268** [comment]
@lxy5513  需要将该环境conda的python与openpose编译,才能调用openpose python API  ，您的文件里的这句话我不怎么懂，能不能说具体点。我不知怎么编译，是需要在下载CMU的那个openpose进行编译吗？

**Comment by lxy5513** [comment]
是的 你需要先编译完成这一步。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wangxiaobai2268"<notifications@github.com&gt;; 
发送时间: 2020年5月21日(星期四) 下午4:16
收件人: "lxy5513/videopose"<videopose@noreply.github.com&gt;; 
抄送: "轻狂书生"<1169360090@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lxy5513/videopose] from openpose import pyopenpose as op求助 (#35)





 
@lxy5513  需要将该环境conda的python与openpose编译,才能调用openpose python API  ，您的文件里的这句话我不怎么懂，能不能说具体点。我不知怎么编译，是需要在下载CMU的那个openpose进行编译吗？

**Comment by lxy5513** [comment]
@wangxiaobai2268 
是的 你需要先编译openpose 完成这一步

https://github.com/lxy5513/videopose/blob/master/joints_detectors/openpose/main.py#L15
