### ISSUE TITLE
live estimation with differend 2d keypoints detector

### ISSUE THREAD

**Issue by sivlab** [lxy5513/videopose#36]
- Is it possible to run the "animation.py" with another 2d detector (instead of OpenPose)?
- In the "animation.py", what is the 3d pose estimator? VideoPose3D from Facebook?

**Comment by lxy5513** [comment]
> Is it possible to run the "animation.py" with another 2d detector (instead of OpenPose)?
In the "animation.py", what is the 3d pose estimator? VideoPose3D from Facebook?

Yes, you can freely choose other 2d detector, 3D pose estimator is derived from facebook videopose3d

**Comment by sivlab** [comment]
Thanks. Can i message you (e.g. email) from another general question?
