### ISSUE TITLE
Lifting from 2D keypoints ?

### ISSUE THREAD

**Issue by timtensor** [lxy5513/videopose#4]
Hello , if i understand correctly, first you do 2D pose estimation and then lift them up for 3d pose estimation by regressing on 2D joint points ?  If so , can it be extended to posenet ?

**Comment by lxy5513** [comment]
@timtensor extended to pose net , do you mean use other 2d keypoints detectors to extract 2d joints coordinations for videopose? If so, that’s right

**Comment by timtensor** [comment]
yes, thank you ! do you know what format should i have the input ? i have a vector which `17x2` and has the following keypoint structure 

`For Posenet 'nose', 0 'leftEye', 1 'rightEye', 2 'leftEar', 3 'rightEar', 4 'leftShoulder', 5 'rightShoulder', 6 'leftElbow', 7 'rightElbow', 8 'leftWrist', 9 'rightWrist', 10 'leftHip', 11 'rightHip', 12 'leftKnee', ' 13 rightKnee', 14 'leftAnkle', 15 'rightAnkle' 16`

**Comment by lxy5513** [comment]
Yes, That is COCO keypoints, you need input (N, 17, 2) format. N represents the video frame numbers.
you can refer this https://github.com/lxy5513/videopose/blob/master/tools/hrnet_video.py#L79

**Comment by timtensor** [comment]
Thank you ! I guess `N` is the total number of video frames in the entire video sequence , right ?

**Comment by lxy5513** [comment]
Yes, you are right

**Comment by timtensor** [comment]
Thank you for your super fast , response! I will try it in coming weeks and keep you updated.

**Comment by timtensor** [comment]
Sorry just a quick question, I looked into your readme. could you please point out where to put the pre trained models , for video pose and also hrnet? I guess we need both of them , to run the 

`python tools/hrnet_video.py --viz-video /path/to/video.mp4` ?

**Comment by lxy5513** [comment]
for hrnet model you can refer this: 
https://github.com/lxy5513/videopose/blob/master/joints_detectors/hrnet/pose_estimation/video.py#L79 . 
<br>
for yolov3 model:
joints_detectors/hrnet/lib/detector/yolo/ 
you can refer this: 
https://github.com/lxy5513/videopose/blob/master/joints_detectors/hrnet/lib/detector/yolo/human_detector.py#L55
<br>
for videopose model:
https://github.com/lxy5513/videopose/blob/master/common/arguments.py#L29 

by the way:
you can change the model path to what you want

**Comment by timtensor** [comment]
Thanks a lot ! unfortunately, I have only a CPU enabled machine at this moment . so i cannot seem to run the code .

**Comment by lxy5513** [comment]
sorry, I am not yet run it in CPU env, so I afraid hardly to help you

**Comment by timtensor** [comment]
no problem, I will see what i can do , I seem to have the following error so i am looking into it 

```
`  File "tools/hrnet_video.py", line 149, in <module>
    main()
  File "tools/hrnet_video.py", line 79, in main
    keypoints = generate_kpts(video_name)
  File "/home/tm/pf/videopose/joints_detectors/hrnet/pose_estimation/video.py", line 116, in generate_kpts
    pose_model = model_load(cfg)
  File "/home/tm/pf/videopose/joints_detectors/hrnet/pose_estimation/video.py", line 81, in model_load
    state_dict = torch.load(model_file_name)
  File "/home/tm/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/tm/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
  File "/home/tm/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 537, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/tm/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "/home/tm/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 95, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/tm/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

`
```
