### ISSUE TITLE
  Issue with File "C:\pf\videopose\tools\..\common\camera.py", line 15, in normalize_screen_coordinates     assert X.shape[-1] == 2 AssertionError

### ISSUE THREAD

**Issue by timtensor** [lxy5513/videopose#5]
Hi , 
I am trying to run your code in windows machine which has a NVDIA GPU  I seem to have the following error 

`  File "C:\pf\videopose\tools\..\common\camera.py", line 15, in normalize_screen_coordinates
    assert X.shape[-1] == 2
AssertionError`

Followed by the error 
`CUDA error: device-side assert triggered
CUDA error: device-side assert triggered
CUDA error: device-side assert triggered`

At this moment , i am just trying to run the following 

`python tools/hrnet_video.py --viz-video C:\pf\videopose\Squat.mp4`

I was wondering if you were familiar with the above ?

**Comment by lxy5513** [comment]
@timtensor  matbe you should check the X shape, X is keypoints, which shape should be (N, 17, 2)

**Comment by lxy5513** [comment]
see this https://github.com/lxy5513/videopose/blob/master/tools/hrnet_video.py#L89

**Comment by timtensor** [comment]
Hi , thanks . Could it be that i have not loaded the pre trained model for video pose ?  Basically i thought , the hrnet detections would work independently , like a seperate module  where you could just get the 2d detection points.  ( i have not used any other detection types)
The only change , i did was to put the pre trained models you provided in the directory structure - 

`C:\pf\videopose\joints_detectors\hrnet\models\pytorch\pose_coco`
to align itself with the code .

**Comment by lxy5513** [comment]
Yes， the hrnet detections would work independently。 you can debug the result by print(keypoints.shape) in  https://github.com/lxy5513/videopose/blob/master/tools/hrnet_video.py#L89

**Comment by timtensor** [comment]
thanks , i had tried that, but i think the program already fails before reaching that part of the code. It seems weird .

I think its related to perhaps enviroment. I am on a native windows machine with cudnn, cuda toolkit and drivers installed. But i have chosen `python3.7` , could that be the reason ?

**Comment by lxy5513** [comment]
what's the error information of the program, what's the result of `print(keypoints.shape) `

**Comment by timtensor** [comment]
the following i get 

`generat keypoints by hrnet...
  0%|                                  [](url)                                                                                                                                                  | 0/2679 [00:00<?, ?it/s]expected a non-empty list of Tensors
  0%|                                                                                                                                                                            | 1/2679 [00:00<42:56,  1.04it/s]expected a non-empty list of Tensors
  0%|▏                                                                                                                                                                           | 2/2679 [00:01<31:38,  1.41it/s]C:/w/1/s/tmp_conda_3.7_044431/conda/conda-bld/pytorch_1556686009173/work/aten/src/THC/THCTensorIndex.cu:308: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/w/1/s/tmp_conda_3.7_044431/conda/conda-bld/pytorch_1556686009173/work/aten/src/THC/THCTensorIndex.cu:308: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/w/1/s/tmp_conda_3.7_044431/conda/conda-bld/pytorch_1556686009173/work/aten/src/THC/THCTensorIndex.cu:308: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
C:/w/1/s/tmp_conda_3.7_044431/conda/conda-bld/pytorch_1556686009173/work/aten/src/THC/THCTensorIndex.cu:308: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.`

Screnshot [https://drive.google.com/open?id=1WcVmrhGe5hLhh-qsEKnCsel_Xx-DiaFj](url)

**Comment by lxy5513** [comment]
you can try this :
`cd VideoPose3D/joints_detectors/hrnet/lib`
`make`

**Comment by timtensor** [comment]
thanks , it seems i have the following issue (enviroment - CUDA) . I have installed CUDA version 10.1 ( do you think that could be an issue ?? 

`(base) C:\pf\videopose\joints_detectors\hrnet\lib\nms>python setup_linux.py build_ext --inplace
Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 44, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME`

But i have already set my enviroment variables pointing to the binaries for the CUDA tool kit and driver . Do you have any suggestions ?

**Comment by lxy5513** [comment]
may is this. sorry I run in linux env, by set `LD_LIBRARY_PATH` to point out CUDA env , but I don't how to set in windows

**Comment by lxy5513** [comment]
what is you $CUDAHOME and  $PATH ?

**Comment by timtensor** [comment]
yes much easier with linux , but unfortunately at this moment i dont have linux 👎 , i checked my variables 

`CUDA PATH `
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1`
and for nvtools 
`C:\Program Files\NVIDIA Corporation\NvToolsExt\bin\x64` , I guess you were asking those ?

I think you need to hard code that part ? Perhaps it is simpler in linux . (from the code it looks like that)

printing out the os.environ i get 
`'CUDA_PATH': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1', '
CUDA_PATH_V10_1': 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1'`

**Comment by lxy5513** [comment]
maybe is your cuda version incompatible:

try this:
```
conda uninstall cuda92 -y
conda uninstall cuda90 -y
conda uninstall pytorch -y
conda uninstall cudatoolkit -y
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch -y
```

**Comment by lxy5513** [comment]
just now, I try this version `linux-64::pytorch-1.0.1-py3.7_cuda10.0.130_cudnn7.4.2_2`    
it work

**Comment by timtensor** [comment]
thanks for the input. I will change os to ubuntu , i guess it should work then . I will close this issue .Its windows related issue . Thanks a lot for your help. I do have a virtual machine but the virtual machine cannot access the NVDIA graphics card . So its not that helpful there
