### ISSUE TITLE
No Moudle named "ipdb"

### ISSUE THREAD

**Issue by WonderLoL** [lxy5513/videopose#7]
I have tried to run the handle Video by hrnet and handle video by alphapose, but I am not successed, it have the error No Moudle named "ipdb", I don't know how to solve it

**Comment by WonderLoL** [comment]
I have install the pytorch 1.1, I don't know is the Environment true?

**Comment by lxy5513** [comment]
pip install ipdb

**Comment by WonderLoL** [comment]
> pip install ipd
 can I Add in WeChat with you?   I wan't to learn more but don't konw how to learn it ?
