### ISSUE TITLE
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

### ISSUE THREAD

**Issue by wongkwan** [lxy5513/videopose#9]
how to solve this problem? thank you for your answer.

**Comment by lxy5513** [comment]
you description is too simple.

**Comment by wongkwan** [comment]
when I run your alphapose_video.py, it reported the errort ：it is not currently possible to manually set the aspect on 3D axes.        The incorrect sentence is in the visualization file， and it is ax.set_aspect('equal').

**Comment by lxy5513** [comment]
if you get 3D joints and 2D keypoints, and draw them, you can 
`from tools.utils import draw_3Dimg `  
draw_3Dimg(pos_3D, image, display=1, kpt2D=keypoints )

**Comment by WinstonDeng** [comment]
I hat same question, and can't solve it. 
from tools.utils import draw_3Dimg 
Where it need to be use? Thanks for your answer.

**Comment by WinstonDeng** [comment]
> when I run your alphapose_video.py, it reported the errort ：it is not currently possible to manually set the aspect on 3D axes. The incorrect sentence is in the visualization file， and it is ax.set_aspect('equal').
Do you solve it? I have same question, but don't know how to fix it.

**Comment by andiconda** [comment]
to install older version matplotlib 2.2. for me it works.
$ pip install matplotlib==2.2
maybe matplotlib 3 is only for python3. i am not sure of reasons. but it works.

**Comment by weidalin** [comment]
> to install older version matplotlib 2.2. for me it works.
> $ pip install matplotlib==2.2
> maybe matplotlib 3 is only for python3. i am not sure of reasons. but it works.

matplotlib 2.2 ,it work for my python3 too
